[package]
name = "bounce"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bounce"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]
